[tool.poetry]
name = "hyphenn-de"
version = "0.1.0"
description = ""
authors = ["Markus Siemens <markus@m-siemens.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.10"
tensorflow = "^2.13.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
